name: Release
description: |
  リリースを作成します
inputs:
  bump-level:
    description: |
      バージョンを上げるレベルを指定します
    required: true
  token:
    description: |
      GitHubのトークン
    required: true
  username:
    description: |
      GitHubのユーザ名
    required: false
    default: github-actions[bot]
  email:
    description: |
      GitHubのメールアドレス
    required: false
    default: github-actions[bot]@users.noreply.github.com
runs:
  using: composite
  steps:
    - uses: actions/checkout@v4

    - name: Bump version and create release
      env:
        USERNAME: ${{ inputs.username }}
        EMAIL: ${{ inputs.email }}
        BUMP_LEVEL: ${{ inputs.bump-level }}
        GITHUB_TOKEN: ${{ inputs.token }}
      run: |
        git config --global user.name "${USERNAME}"
        git config --global user.email "${EMAIL}"
        version="$(.github/scripts/bump.sh "${BUMP_LEVEL}")"
        gh release create "${version}" --title "${version}"--generate-notes
      shell: bash
