name: Release
description: |
  リリースを作成します
inputs:
  bump-level:
    description: |
      バージョンを上げるレベルを指定します
    required: true
    default: patch
    validation:
      pattern: '^(major|minor|patch)$'
runs:
  using: composite
  steps:
    - uses: actions/checkout@v4

    - env:
        USERNAME: github-actions[bot]
        EMAIL: github-actions[bot]@users.noreply.github.com
        BUMP_LEVEL: ${{ inputs.bump-level }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "${USERNAME}"
        git config --global user.email "${EMAIL}"
        version="$(.github/scripts/bump.sh "${BUMP_LEVEL}")"
        gh release create "${version}" --title "${version}"--generate-notes
