name: Update Minor Version
on:
  push:
    branches:
      - main
env:
  bump-level: major
jobs:
  update_minor_version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update Minor Version
        uses: ./.github/actions/release
        with:
          bump-level: ${{ env.bump-level }}
          token: ${{ secrets.GITHUB_TOKEN }}
